### PR TITLE
More options for MOAB and DAGMC

### PR DESCRIPTION
**Pull request by gonuke**
1. Each of MOAB and DAGMC can be added with no path, in which case some default path is searched.
2. Each of MOAB and DAGMC can be added with specific paths
3. If not specified at all, no search for MOAB or DAGMC will be done

### CODE REVIEW

**Comment by gonuke** [comment]
Do we need test more build combinations?

**Comment by pshriwise** [comment]
There's something weird about the source/target branches here. It looks like `moab_dagmc_option` is based on `pyne/develop`. Is that the issue?

**Comment by gonuke** [comment]
Is this better now @pshriwise ?

**Comment by bam241** [comment]
Do we want CI to test each build option available here ?

**Comment by pshriwise** [comment]
@bam241 that's probably a good idea if it isn't too difficult to add the configurations. 

Looking at `.circleci/config.yml`, it seems like it wouldn't be too difficult to do. There could be questions about how much time it would add to CI I suppose. Let's find out...

**Comment by pshriwise** [comment]
The only build we need to add is one with `--moab` specified and without `--dagmc`. We get 4 parallel jobs on CI, so I don't see why we wouldn't add that one I guess. There may be more once we get Python3 working with PyMOAB, but each job takes ~6 min. I don't think we'll be pushing up against any time limits here.

**Comment by pshriwise** [comment]
One further thought is whether or not a build with only `--dagmc` is feasible. Thanks to @ljacobson64's work on setting DAGMC's RPATH, it should be able to find the MOAB libraries it needs to function on its own, allowing the `dagmc` module to work without having pymoab present.

And another question is whether or not there's a point in having the `dagmc` module available without a PyNE mesh backed by `pymoab`. My feeling is that there isn't one currently, but maybe this is something to keep in mind for the future.

**Comment by bam241** [comment]
@pshriwise I have a PR (#66  ) to build the image for each of those, I'll update the CI to use them :)

**Comment by pshriwise** [comment]
Awesome. This LGTM then. @bam merge away!

**Review by pshriwise — APPROVED** [review]

**Comment by bam241** [comment]
thx @gonuke @pshriwise 
merging

**Comment by bam** [comment]
And hello again! :D

> Awesome. This LGTM then. @bam merge away!

@pshriwise please type full name of bam241 when mention him next time ;)

**Pull request merged**
